[CI] Upload standalone archives to releases

diff --git a/.github/workflows/coq-alpine.yml b/.github/workflows/coq-alpine.yml
--- a/.github/workflows/coq-alpine.yml
+++ b/.github/workflows/coq-alpine.yml
@@ -6,6 +6,8 @@ on:
   pull_request:
   merge_group:
   workflow_dispatch:
+  release:
+    types: [published]
   schedule:
     - cron: '0 0 1 * *'
 
@@ -91,12 +93,115 @@ jobs:
     - name: display per-line timing info
       run: etc/ci/github-actions-display-per-line-timing.sh
 
+  test-standalone:
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+        - alpine: 'edge'
+#        - alpine: 'latest-stable'
+    runs-on: ubuntu-latest
+    name: test-standalone-${{ matrix.alpine }}
+    needs: build
+    steps:
+    - uses: actions/checkout@v4
+    - name: Download standalone ${{ matrix.alpine }}
+      uses: actions/download-artifact@v3
+      with:
+        name: standalone-${{ matrix.alpine }}
+        path: dist-${{ matrix.alpine }}/
+    - name: List files
+      run: find dist-edge
+    - name: Rename files
+      run: |
+        mkdir dist
+        mv dist-${{ matrix.alpine }}/standalone.tar.gz dist/fiat-crypto-alpine-${{ matrix.alpine }}.tar.gz
+        find dist
+        tar -tvf dist/fiat-crypto-alpine-${{ matrix.alpine }}.tar.gz
+    - name: Unpack files
+      run: |
+        cd dist
+        tar -xzvf fiat-crypto-alpine-${{ matrix.alpine }}.tar.gz
+        ls -la .
+    - name: Test files (host)
+      run: |
+        cd dist
+        for prog in word_by_word_montgomery unsaturated_solinas saturated_solinas base_conversion; do
+          echo "::group::file $prog"
+          file $prog
+          echo "::endgroup::"
+          echo "::group::ldd $prog"
+          ldd $prog
+          echo "::endgroup::"
+          echo "::group::$prog"
+          ./$prog -h || echo "::error::$prog does not run on host" # does not work yet
+          echo "::endgroup::"
+        done
+    - uses: jirutka/setup-alpine@v1
+      with:
+        branch: ${{ matrix.alpine }}
+        extra-repositories: https://dl-cdn.alpinelinux.org/alpine/edge/testing
+    - name: Test files (container)
+      shell: alpine.sh {0}
+      run: |
+        cd dist
+        for prog in word_by_word_montgomery unsaturated_solinas saturated_solinas base_conversion; do
+          echo "::group::file $prog"
+          file $prog
+          echo "::endgroup::"
+          echo "::group::ldd $prog"
+          ldd $prog
+          echo "::endgroup::"
+          echo "::group::$prog"
+          ./$prog -h
+          echo "::endgroup::"
+        done
+
+  publish-standalone:
+    runs-on: ubuntu-latest
+    needs: build
+    permissions:
+      contents: write  # IMPORTANT: mandatory for making GitHub Releases
+    steps:
+    - uses: actions/checkout@v4
+    - name: Download standalone edge
+      uses: actions/download-artifact@v3
+      with:
+        name: standalone-edge
+        path: dist-edge/
+    - name: List files
+      run: find dist-edge
+    - name: Unpack files
+      run: |
+        mkdir dist
+        mv dist-edge/standalone.tar.gz dist/fiat-crypto-alpine-edge.tar.gz
+        find dist
+        tar -tvf dist/fiat-crypto-alpine-edge.tar.gz
+    - name: Upload artifacts to GitHub Release
+      env:
+        GITHUB_TOKEN: ${{ github.token }}
+      # Upload to GitHub Release using the `gh` CLI.
+      # `dist/` contains the built packages
+      run: >-
+        gh release upload
+        '${{ github.ref_name }}' dist/**
+        --repo '${{ github.repository }}'
+      if: ${{ startsWith(github.ref, 'refs/tags/') && github.event_name == 'release' }}
+
   alpine-check-all:
     runs-on: ubuntu-latest
-    needs: [build]
+    needs: [build, test-standalone, publish-standalone]
     if: always()
     steps:
     - run: echo 'build passed'
       if: ${{ needs.build.result == 'success' }}
+    - run: echo 'test-standalone passed'
+      if: ${{ needs.test-standalone == 'success' }}
+    - run: echo 'publish-standalone passed'
+      if: ${{ needs.publish-standalone.result == 'success' }}
     - run: echo 'build failed' && false
       if: ${{ needs.build.result != 'success' }}
+    - run: echo 'test-standalone failed' && false
+      if: ${{ needs.test-standalone != 'success' }}
+    - run: echo 'publish-standalone failed' && false
+      if: ${{ needs.publish-standalone.result != 'success' }}
