Update coq.yml

diff --git a/.github/workflows/coq.yml b/.github/workflows/coq.yml
--- a/.github/workflows/coq.yml
+++ b/.github/workflows/coq.yml
@@ -77,7 +77,7 @@ jobs:
       run: etc/ci/github-actions-make.sh -j2 test-c-files
       if: env.SKIP_DISPLAY_TEST != '1'
     - name: test for adx
-      run: if ! etc/assert-adx.sh; then echo -e "\e[31mWARNING: adx instruction not found\e[0m"; export SKIP_ICC=1; false; fi
+      run: 'if ! etc/assert-adx.sh; then echo -e "\e[31mWARNING: adx instruction not found\e[0m"; export SKIP_ICC=1; false; fi'
       continue-on-error: true
       if: env.SKIP_DISPLAY_TEST != '1'
     - name: selected-test selected-bench
