Disable icc tests when adx is not present

diff --git a/.github/workflows/coq.yml b/.github/workflows/coq.yml
--- a/.github/workflows/coq.yml
+++ b/.github/workflows/coq.yml
@@ -76,6 +76,10 @@ jobs:
     - name: standalone-ocaml c-files test-c-files
       run: etc/ci/github-actions-make.sh -j2 test-c-files
       if: env.SKIP_DISPLAY_TEST != '1'
+    - name: test for adx
+      run: if ! etc/assert-adx.sh; then echo -e "\e[31mWARNING: adx instruction not found\e[0m"; export SKIP_ICC=1; false; fi
+      continue-on-error: true
+      if: env.SKIP_DISPLAY_TEST != '1'
     - name: selected-test selected-bench
       run: ALLOW_DIFF=1 etc/ci/github-actions-make.sh -j2 selected-test selected-bench
       if: env.SKIP_DISPLAY_TEST != '1'
